version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "1433:1433"
    networks:
      - lfnetwork
  limeflighttakehomechallenge:
    image: ${DOCKER_REGISTRY-}limeflighttakehomechallenge
    build:
      context: .
      dockerfile: LimeFlightTakeHomeChallenge/Dockerfile
    depends_on:
      - db
networks:
  lfnetwork:
    driver: bridge